[package]
name = "louisbotrs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
plotters = "0.3.7"
poise = "0.6.1"
rand = "0.9.2"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
